name: BattleRoyale
version: '1.0-SNAPSHOT'
main: org.Foxraft.battleRoyale.BattleRoyale
api-version: '1.21'
softdepend: [PlaceholderAPI]
commands:
  br:
    description: Battle Royale commands
    usage: /<command> [subcommand]
    aliases: [battleroyale]

permissions:
  br.admin:
    description: Admin commands for Battle Royale
    default: op
  br.team:
    description: Allows players to use team commands
    default: true