name: BattleRoyale
version: '1.0-SNAPSHOT'
main: org.Foxraft.battleRoyale.BattleRoyale
api-version: '1.21'
commands:
  br:
    permission: br.use
    description: Battle Royale command
    usage: /<command>
    aliases: [battleroyale]
    subcommands:
      team:
        permission: br.team
        description: Team commands
        usage: /<command> team <subcommand>
        subcommands:
          invite:
            permission: br.team
            description: Invite a player to your team
            usage: /<command> team invite <player>
          accept:
            permission: br.team
            description: Invite a player to your team
            usage: /<command> team invite <player>
          leave:
            permission: br.team
            description: Leave your team
            usage: /<command> team leave
          list:
            permission: br.team
            description: List all teams
            usage: /<command> team list <page>
